version: "3.9"
name: quackly

networks:
    quackly:

services:

    nginx:
        image: nginx:stable
        volumes: 
            - ./html:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8282:80
        depends_on:
            - php
            - db
        networks:
            - quackly

    php:
        build: 
            context: .
            dockerfile: ./Dockerfile-php
        volumes: 
            - ./html:/var/www/html
        ports:
            - 9000:9000
        networks:
            - quackly

    db:
        image: mysql:latest
        volumes: 
            - ./db:/var/lib/mysql
        ports:
            - 3308:3306
        environment:
            - MYSQL_DATABASE=quackly
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        networks:
            - quackly
