<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMyxPCXd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMyxPCXd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMyxPCXd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMyxPCXd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMyxPCXd\App_KernelDevDebugContainer([
    'container.build_hash' => 'MyxPCXd',
    'container.build_id' => '8bf0167e',
    'container.build_time' => 1687949118,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMyxPCXd');
